# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usda_nutrition', '0002_nutrientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientdata',
            name='lower_error_bound',
            field=models.DecimalField(decimal_places=3, help_text=b'Lower 95% error bound.', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientdata',
            name='maximum',
            field=models.DecimalField(decimal_places=3, help_text=b'Maximum value.', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientdata',
            name='minimum',
            field=models.DecimalField(decimal_places=3, help_text=b'Minimum value.', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientdata',
            name='upper_error_bound',
            field=models.DecimalField(decimal_places=3, help_text=b'Upper 95% error bound.', max_digits=13, null=True),
        ),
    ]
