# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usda_nutrition', '0003_auto_20160920_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='food_description',
            field=models.ForeignKey(help_text=b'5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.', on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='usda_nutrition.FoodDescription'),
        ),
        migrations.AlterField(
            model_name='nutrientdata',
            name='food_description',
            field=models.ForeignKey(help_text=b'5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.', on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_data', to='usda_nutrition.FoodDescription'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='food_description',
            field=models.ForeignKey(help_text=b'5-digit Nutrient Databank number that uniquely identifies a food item. If this field is defined as numeric, the leading zero will be lost.', on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='usda_nutrition.FoodDescription'),
        ),
    ]
